"""Read/transaction-only checks on an already-migrated PostgreSQL test target."""

from uuid import uuid4

from sqlalchemy import inspect, text

from app.db import engine

if engine.dialect.name != "postgresql" or engine.url.database != "handoff_test":
    raise SystemExit("Requires an isolated PostgreSQL database named handoff_test")

indexes = {i["name"] for i in inspect(engine).get_indexes("documents")}
assert "ix_documents_fts" in indexes
assert "ix_documents_case_active" in indexes
with engine.connect() as connection:
    transaction = connection.begin()
    try:
        tenant, event, policy = str(uuid4()), str(uuid4()), str(uuid4())
        connection.execute(
            text("INSERT INTO tenants(id,name) VALUES (:id,:name)"),
            {"id": tenant, "name": "Schema verification"},
        )
        connection.execute(
            text(
                "INSERT INTO events(id,tenant_id,seq,kind,summary,data,created_at) VALUES (:id,:tenant,1,'test','original','{}',0)"
            ),
            {"id": event, "tenant": tenant},
        )
        connection.execute(
            text(
                "INSERT INTO templates(id,tenant_id,family,version,name,source,destination,rules,rule_hash,created_at) VALUES (:id,:tenant,:id,1,'Test','A','B','[]','testhash',0)"
            ),
            {"id": policy, "tenant": tenant},
        )
        for table, row, field in [("events", event, "summary"), ("templates", policy, "name")]:
            # Keep the expected trigger exception inside PostgreSQL. All identifiers
            # below come from this fixed list and UUIDs generated by this script.
            connection.execute(
                text(f"""DO $$ BEGIN
                BEGIN
                    UPDATE {table} SET {field}='tampered' WHERE id='{row}';
                    RAISE EXCEPTION 'Immutable history update was permitted';
                EXCEPTION WHEN raise_exception THEN
                    IF SQLERRM <> 'Audit is append-only' THEN RAISE; END IF;
                END;
            END $$;""")
            )
        assert connection.scalar(
            text(
                "SELECT to_tsvector('simple','payment_terms: 30 days') @@ plainto_tsquery('simple','payment_terms')"
            )
        )
    finally:
        transaction.rollback()
print(
    "PostgreSQL migration indexes, immutable triggers and text search passed; verification rows rolled back."
)
